import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { InferGetStaticPropsType } from "next";
import { createClient } from "next-sanity";
import Navbar from "../components/Navbar";
import HeroSection from "@/components/Hero";

const inter = Inter({ subsets: ["latin"] });

type pet = {
  name: string;
  yearOfBirth: number;
  _createdAt: string;
  _id: string;
  _rev: string;
  _type: string;
  _updatedAt: string;
};

export default async function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <HeroSection />
      </main>
    </>
  );
}
